repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --all
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --all-targets
        language: system
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/NSPBot911/ty-pre-commit
    rev: v0.0.15
    hooks:
      - id: ty-check
        types_or: [ python, pyi ]
        additional_dependencies: [pytest, yamloom]
  - repo: https://github.com/denehoffman/yamloom
    rev: yamloom-v0.5.4
    hooks:
      - id: yamloom-sync
        files: ^(\.github/workflows/.*\.ya?ml|\.yamloom\.py)$
