---
name: Release Please
"on":
  push:
    branches:
      - main
jobs:
  release-please:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
        id: release
      - name: Checkout Repository
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
        uses: actions/checkout@v6
      - name: Setup Rust
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Rust Tool
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-workspaces
      - if: ${{ fromJSON(steps.release.outputs.releases_created) }}
        run: cargo workspaces publish --from-git --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --yes